# Generated by Django 2.1.5 on 2019-01-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
