# Generated by Django 2.0 on 2019-02-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoplay', '0002_auto_20190120_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_One_Stimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('vid_id', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=10, unique=True)),
                ('vid_url', models.CharField(max_length=100)),
            ],
        ),
    ]
