# Generated by Django 2.1.5 on 2019-02-25 17:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0003_score_one_stimulus_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreOneStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('vid_id', models.CharField(max_length=10)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField()),
            ],
            managers=[
                ('userScore', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=10, unique=True)),
                ('vid_url', models.CharField(max_length=256, unique=True)),
            ],
            managers=[
                ('urlobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Score_One_Stimulus',
        ),
        migrations.DeleteModel(
            name='Video_Url',
        ),
    ]
