# Generated by Django 2.0 on 2019-03-14 00:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0004_auto_20190225_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTwoStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('vid_id1', models.CharField(max_length=10)),
                ('vid_id2', models.CharField(max_length=10)),
                ('preference', models.CharField(blank=True, max_length=10, null=True)),
            ],
            managers=[
                ('userPref', django.db.models.manager.Manager()),
            ],
        ),
    ]
