# Generated by Django 2.0 on 2019-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190128_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreOneStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('vid_id', models.CharField(max_length=10)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=10, unique=True)),
                ('vid_url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
