# Generated by Django 2.1.5 on 2019-02-06 18:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_scoreonestimulus_videourl'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scoreonestimulus',
            managers=[
                ('userScore', django.db.models.manager.Manager()),
            ],
        ),
    ]
