# Generated by Django 2.0 on 2019-02-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190218_2304'),
        ('feedback', '0005_auto_20190207_0435'),
    ]

    operations = [
    ]
